title: "Meu Portfólio"
description: "Bem-vindo ao meu portfólio online!"
url: "https://edisonepjr.github.io/meu-portifolio"
theme: "minima"
author:
  name: "Edison Júnior"
  email: "edisonpereirajr@hotmail.com"
  github: "edisonepjr"
  linkedin: "edison-junior-46a939232"
